steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/LalapetaDhanu/helloworld-project.git', '--branch', 'main', 'workspace']

- name: 'maven:3.6.3-jdk-11'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'cd workspace && mvn clean install'
